version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: investbuddy-agent
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ../data:/data  # Très important pour écrire dans prod_data.csv
    networks:
      - investbuddy_net

networks:
  investbuddy_net:
    external: true 